# Generated by Django 4.0.3 on 2022-03-17 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('units', models.IntegerField(null=True)),
                ('lecture', models.FileField(blank=True, null=True, upload_to='lecture/', verbose_name='Lecture')),
                ('plan', models.FileField(blank=True, null=True, upload_to='plan/', verbose_name='Plan')),
            ],
        ),
        migrations.CreateModel(
            name='Researche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField(auto_created=True)),
                ('research', models.ManyToManyField(to='material.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Course_Description_of_Specialized_Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('one', 'one'), ('tow', 'tow'), ('three', 'three'), ('four', 'four')], max_length=50)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.branch')),
                ('materials', models.ManyToManyField(to='material.subject')),
            ],
            options={
                'verbose_name': 'Course Description of Specialized Course',
                'verbose_name_plural': 'Course Description of Specialized Courses',
            },
        ),
        migrations.CreateModel(
            name='Course_description_of_common_materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('one', 'one'), ('tow', 'tow'), ('three', 'three'), ('four', 'four')], max_length=50)),
                ('common_materials', models.ManyToManyField(to='material.subject')),
            ],
            options={
                'verbose_name': 'Course description of common material',
                'verbose_name_plural': 'Course description of common materials',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('1s', '1s'), ('2nd', '2nd')], max_length=10)),
                ('level', models.CharField(choices=[('one', 'one'), ('tow', 'tow'), ('three', 'three'), ('four', 'four')], max_length=50)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.branch')),
                ('subjects', models.ManyToManyField(related_name='courses', to='material.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Academic_Program_Description_Forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.subject')),
            ],
            options={
                'verbose_name': 'Academic Program Description Form',
                'verbose_name_plural': 'Academic Program Description Forms',
            },
        ),
    ]
