# Generated by Django 4.0.3 on 2022-03-17 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('mobile', models.CharField(max_length=40)),
                ('gmail', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Gmail')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('female', 'female')], max_length=20)),
                ('age', models.IntegerField(verbose_name='Age')),
                ('education', models.CharField(max_length=500, verbose_name='Education')),
                ('degree', models.CharField(max_length=100, verbose_name='Degree')),
                ('honor', models.CharField(max_length=500, verbose_name='Honors And Awards')),
                ('joindate', models.DateField(auto_now_add=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.branch', verbose_name='Branch')),
                ('teacing', models.ManyToManyField(related_name='teachers', to='material.subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('mobile', models.CharField(max_length=40, null=True)),
                ('gmail', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Gmail')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('female', 'female')], max_length=20)),
                ('age', models.IntegerField(verbose_name='Age')),
                ('level', models.CharField(choices=[('one', 'one'), ('tow', 'tow'), ('three', 'three'), ('four', 'four')], max_length=20)),
                ('joindate', models.DateField(auto_now_add=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.branch')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.teacher'),
        ),
    ]
