# Generated by Django 4.0.3 on 2022-03-17 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_teacher_student_subject_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions_Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField(auto_created=True)),
                ('subject', models.FileField(blank=True, null=True, upload_to='questions/', verbose_name='subject')),
                ('term', models.CharField(choices=[('First', 'First'), ('Second', 'Second')], max_length=20, verbose_name='Term')),
                ('solution', models.FileField(blank=True, null=True, upload_to='questions/', verbose_name='Solution')),
                ('level', models.CharField(choices=[('one', 'one'), ('tow', 'tow'), ('three', 'three'), ('four', 'four')], max_length=50)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.branch')),
            ],
            options={
                'verbose_name': 'Questions Bank',
            },
        ),
    ]
