# Generated by Django 4.0.3 on 2022-03-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_questions_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Full Name'),
        ),
    ]
