# Generated by Django 4.0.3 on 2022-03-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0004_alter_student_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(null=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('female', 'female')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('one', 'one'), ('tow', 'tow'), ('three', 'three'), ('four', 'four')], max_length=20, null=True),
        ),
    ]
