# Generated by Django 4.0.3 on 2022-03-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0011_alter_course_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='image',
            field=models.ImageField(default=1, upload_to='branche_pict/'),
            preserve_default=False,
        ),
    ]
