# Generated by Django 4.0.3 on 2022-04-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0013_linke_teacher_image_teacher_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions_bank',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
