# Generated by Django 4.0.3 on 2022-04-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0014_questions_bank_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions_bank',
            name='course',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
