# Generated by Django 4.0.3 on 2022-05-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0016_alter_course_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic_program_description_forms',
            name='content',
            field=models.FileField(blank=True, null=True, upload_to='Academic_Program_Description_Forms/', verbose_name='content'),
        ),
    ]
