# Generated by Django 4.0.3 on 2022-05-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0017_alter_academic_program_description_forms_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd')], max_length=10),
        ),
        migrations.AlterField(
            model_name='course_description_of_common_materials',
            name='stage',
            field=models.CharField(choices=[('one', 'one'), ('two', 'two'), ('three', 'three'), ('four', 'four')], max_length=50),
        ),
        migrations.AlterField(
            model_name='course_description_of_specialized_courses',
            name='stage',
            field=models.CharField(choices=[('one', 'one'), ('two', 'two'), ('three', 'three'), ('four', 'four')], max_length=50),
        ),
    ]
