# Generated by Django 4.0.3 on 2022-05-30 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0019_remove_teacher_teacing_remove_teacher_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions_bank',
            name='course',
        ),
    ]
